In [3]:
import duckdb

con = duckdb.connect()

In [4]:
path = "s3://mateom/graal/embeddings/NAF2025/2026-03-16_gemma_synth.parquet"
n_samples = 1000

In [ ]:
con.execute(f"SELECT setseed({0.5});")
query = f"""
SELECT code, label, embedding
FROM read_parquet('{path}')
USING SAMPLE {n_samples} ROWS
ORDER BY (code, label)
"""

df = con.execute(query).df()
df

,code,label,embedding
0,01.11Y,Culture de céréales diversifiées,"[0.030173147097229958, 0.029588395729660988, 0..."
1,01.11Y,Exploitation d'une activité agricole axée sur ...,"[0.038778554648160934, 0.023314714431762695, 0..."
2,01.11Y,"Intervention sur culture de légumineuse, contr...","[0.040246400982141495, 0.001985842129215598, 0..."
3,01.11Y,Production de graines de niger,"[0.018320737406611443, 0.025719495490193367, 0..."
4,01.11Y,"Production de graines de soja, arachides et ri...","[0.0009564123465679586, 0.037485431879758835, ..."
...,...,...,...
995,96.99H,Activités de bien-être alternatives,"[0.024193717166781425, 0.021492475643754005, 0..."
996,96.99H,"Préposé au parcage, organisation de stationnem...","[0.009673898108303547, 0.013768983073532581, 0..."
997,98.10Y,Ménages produisant pour leur propre compte.,"[0.00983060896396637, 0.03581150248646736, -0...."
998,98.20Y,Cuisine et soins assurés au sein du foyer.,"[0.010468038730323315, 0.023656584322452545, 0..."
999,99.00Y,Activités d'organismes hors territoire national,"[0.013571694493293762, 0.029673704877495766, -..."

In [5]:
con.execute(f"SELECT setseed({0.5});")
query = f"""
SELECT COUNT(DISTINCT(code))
FROM read_parquet('{path}')
"""

df = con.execute(query).df()
df

   count(DISTINCT code)
0                   747

In [7]:
df.loc[0,"embedding"]

array([ 0.03017315,  0.0295884 ,  0.00701701, ..., -0.00229515,
       -0.01122722,  0.00882974], shape=(4096,))

In [1]:
from qdrant_client import QdrantClient
import os
from dotenv import load_dotenv

load_dotenv(override=True)

QDRANT_URL = "http://qdrant:6333"
QDRANT_API_KEY = os.environ["QDRANT_API_KEY"]  # ou None si local

client = QdrantClient(
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY,
    timeout=30
)

/tmp/ipykernel_66813/670185661.py:10: UserWarning: Api key is used with an insecure connection.
  client = QdrantClient(

In [ ]:
from qdrant_client.models import VectorParams, Distance, PointStruct

# CONFIG
COLLECTION_NAME = "test_collection"
VECTOR_SIZE = 4096

# Reset collection
if client.collection_exists(COLLECTION_NAME):
    client.delete_collection(COLLECTION_NAME)

client.create_collection(
    collection_name=COLLECTION_NAME,
    vectors_config=VectorParams(size=VECTOR_SIZE, distance=Distance.COSINE)
)

# Insert 1 point
point = PointStruct(
    id=1,
    vector=[0.1] * VECTOR_SIZE,
    payload={"test": "ok"}
)

client.upsert(
    collection_name=COLLECTION_NAME,
    points=[point]
)

print("✅ Insert OK")

# Insert batch (stress test léger)
points = [
    PointStruct(id=i, vector=[0.1] * VECTOR_SIZE, payload={"i": i})
    for i in range(100)
]

client.upsert(
    collection_name=COLLECTION_NAME,
    points=points
)

print("✅ Batch insert OK")

/tmp/ipykernel_2700/1007922045.py:13: UserWarning: Api key is used with an insecure connection.
  client = QdrantClient(

✅ Insert OK
✅ Batch insert OK

In [13]:
code_hits = client.facet(
    collection_name="original_cleaned",
    key="code",
    exact=True,
    limit=1000
).hits

code_list = {hit.value: hit.count for hit in code_hits}

In [17]:
code_list.keys()

dict_keys(['68.20H', '70.20Y', '68.20G', '96.22Y', '62.10Y', '43.21G', '95.31G', '62.20G', '85.59H', '73.30Y', '82.10Y', '66.30Y', '71.12Y', '85.59G', '69.10Y', '55.20Y', '49.41G', '70.10Y', '43.22G', '96.23Y', '46.19H', '43.32G', '81.30Y', '56.21Y', '47.12H', '73.11Y', '43.31Y', '86.21Y', '86.22Y', '94.99Y', '58.13Y', '32.13Y', '96.99H', '53.20H', '43.22H', '85.52Y', '66.22Y', '74.30Y', '43.33Y', '47.71Y', '68.11Y', '46.90Y', '86.23Y', '43.41H', '56.30Y', '77.11Y', '43.12G', '88.10G', '01.11Y', '69.20Y', '71.11Y', '01.21Y', '80.01Y', '81.22Y', '95.10Y', '10.71H', '01.61Y', '59.20Y', '85.69Y', '88.99H', '01.48J', '55.10Y', '01.13Y', '74.12Y', '58.29Y', '68.32G', '85.53Y', '33.20Y', '71.20H', '43.41G', '74.99Y', '01.50Y', '47.76Y', '46.42Y', '10.71J', '58.12Y', '68.32H', '59.12Y', '86.92Y', '59.11G', '77.22Y', '85.40Y', '01.48G', '43.23Y', '75.00Y', '47.40Y', '47.75Y', '47.22Y', '23.41Y', '73.20Y', '82.20Y', '81.10Y', '10.72Y', '01.45Y', '46.83G', '81.23G', '81.23H', '01.42Y', '01.43Y', '47.74G', '81.21Y', '58.11Y', '77.21Y', '78.20G', '55.90Y', '18.13Y', '15.12Y', '46.50Y', '62.20H', '46.39Y', '68.12Y', '46.34Y', '96.30Y', '62.90Y', '93.12Y', '02.40Y', '02.10Y', '95.24Y', '38.11Y', '46.49Y', '49.33H', '47.63Y', '52.21Y', '56.22Y', '63.10Y', '47.74H', '80.09Y', '14.10Y', '78.10Y', '46.45Y', '47.73Y', '56.11J', '88.99G', '86.96Y', '43.24Y', '01.41Y', '68.31Y', '47.81Y', '01.47Y', '47.24Y', '52.24H', '01.29Y', '47.25Y', '77.32Y', '25.53Y', '47.21Y', '49.42Y', '01.28Y', '01.62Y', '32.12Y', '46.18Y', '13.30Y', '01.24Y', '02.20Y', '43.11Y', '20.42Y', '93.29Y', '25.11Y', '47.77Y', '72.10H', '95.22Y', '32.40Y', '13.99Y', '58.21Y', '93.13Y', '79.12Y', '46.31Y', '11.05Y', '71.20G', '17.23Y', '10.85Y', '47.52G', '46.46Y', '46.38Y', '86.91Y', '47.72G', '47.30Y', '78.20H', '47.55H', '46.81Y', '25.99Y', '47.51Y', '01.22Y', '01.30Y', '46.47Y', '47.64Y', '86.99Y', '95.31H', '47.61Y', '53.20G', '01.25Y', '17.25Y', '90.12Y', '01.19Y', '96.99G', '23.70Y', '47.78G', '25.40Y', '64.19Y', '88.10H', '72.20Y', '10.89Y', '46.64G', '95.21Y', '43.34G', '55.30Y', '82.40Y', '43.91Y', '85.32Y', '46.64K', '46.87Y', '10.82Y', '46.17H', '66.21Y', '46.82Y', '73.12Y', '46.13Y', '46.61Y', '10.39H', '42.22Y', '50.10Y', '37.00Y', '66.19G', '95.23Y', '32.20Y', '47.78H', '43.99G', '16.11Y', '25.61Y', '74.20Y', '60.39Y', '11.01Y', '86.95Y', '46.41Y', '82.92Y', '29.20Y', '47.54Y', '72.10G', '59.13Y', '61.10Y', '86.94G', '01.46Y', '27.40Y', '86.10Y', '87.99G', '49.31H', '20.41Y', '46.23Y', '23.15Y', '51.10Y', '03.11Y', '90.11Y', '46.86Y', '13.91Y', '47.23Y', '46.63Y', '33.14Y', '46.21Y', '01.26Y', '93.19Y', '86.93Y', '88.91J', '85.51Y', '47.92J', '32.99Y', '60.31Y', '96.91Y', '82.99Y', '10.83Y', '77.31Y', '94.12Y', '10.11Y', '46.14Y', '25.12Y', '74.13Y', '77.34Y', '96.21G', '46.48Y', '65.12Y', '46.37Y', '10.13H', '47.11L', '90.20Y', '47.72H', '49.20Y', '64.21Y', '46.84G', '87.30G', '01.14Y', '43.12H', '47.79H', '26.40Y', '63.92Y', '91.21Y', '35.12Y', '87.99H', '01.16Y', '60.10Y', '82.91Y', '66.12Y', '85.20Y', '11.02H', '38.21Y', '85.31Y', '91.22Y', '10.52Y', '42.21Y', '46.32G', '46.44Y', '95.25Y', '47.27H', '23.13Y', '10.39G', '10.32Y', '47.52H', '14.21Y', '46.85Y', '59.14Y', '23.66Y', '56.12Y', '23.63Y', '29.32Y', '33.13Y', '46.16Y', '49.33G', '52.23Y', '82.30Y', '03.21Y', '39.00Y', '46.11Y', '74.11Y', '18.14Y', '31.00H', '66.19H', '46.32H', '25.52Y', '90.39G', '13.93Y', '43.13Y', '46.22Y', '59.11H', '01.23Y', '16.12Y', '92.00Y', '94.91Y', '53.10Y', '77.39Y', '08.12Y', '50.40Y', '47.69Y', '52.22Y', '77.35Y', '10.84Y', '79.90Y', '10.73Y', '26.52Y', '32.50Y', '35.30Y', '25.63Y', '01.48H', '15.20Y', '16.28Y', '36.00Y', '47.82Y', '90.39H', '10.51H', '30.92Y', '35.21Y', '46.15Y', '42.91Y', '47.53Y', '49.41H', '96.10H', '46.33Y', '46.62Y', '50.20Y', '56.11G', '94.20Y', '43.99H', '87.10G', '96.21H', '23.45Y', '23.61Y', '26.12Y', '29.10Y', '50.30Y', '95.29H', '24.20Y', '33.12Y', '03.22Y', '43.35Y', '94.11Y', '10.92Y', '13.10Y', '49.41J', '20.16Y', '10.20Y', '47.91Y', '28.29Y', '30.12Y', '55.40Y', '46.71G', '59.11J', '26.51Y', '47.92G', '88.91G', '13.92Y', '88.91H', '02.30Y', '31.00J', '10.41Y', '25.62Y', '20.59Y', '77.33Y', '88.10J', '11.03Y', '18.12Y', '43.21H', '21.20Y', '41.00H', '08.11Y', '13.96Y', '26.11Y', '43.32H', '47.55G', '84.25Y', '66.29Y', '87.20G', '42.12Y', '47.62Y', '94.92Y', '14.29Y', '47.79G', '08.93Y', '10.51G', '28.22Y', '95.29G', '13.94Y', '17.12Y', '17.21Y', '52.26Y', '07.29Y', '24.45Y', '52.10H', '64.31Y', '85.10Y', '11.04Y', '23.99Y', '25.30Y', '28.12Y', '10.61G', '58.19Y', '63.91Y', '64.92Y', '14.24Y', '26.70Y', '52.25Y', '90.13Y', '18.20Y', '23.32Y', '28.30Y', '43.60Y', '47.27G', '74.14Y', '84.13Y', '87.10J', '01.27Y', '29.31Y', '79.11Y', '84.11Y', '22.26Y', '25.93Y', '35.14Y', '43.50Y', '65.20Y', '20.15Y', '20.30Y', '38.12Y', '43.42J', '46.12Y', '46.64J', '10.12Y', '24.33Y', '41.00G', '43.42G', '47.26Y', '49.50Y', '01.44Y', '27.20Y', '47.92H', '84.23Y', '84.30G', '87.10H', '91.11Y', '01.70Y', '33.17Y', '46.72Y', '49.39Y', '51.21Y', '52.24G', '64.99Y', '65.11Y', '11.02G', '21.10Y', '27.33Y', '28.41Y', '31.00G', '42.13G', '47.11G', '47.11J', '10.31Y', '10.91Y', '15.11Y', '16.23Y', '24.42Y', '24.54Y', '33.15Y', '47.83Y', '59.11K', '64.32Y', '64.91Y', '84.12Y', '93.11Y', '93.21Y', '01.12Y', '03.12Y', '06.10Y', '22.25Y', '25.22Y', '27.52Y', '28.93Y', '35.22Y', '42.99Y', '46.84H', '47.11H', '87.20H', '25.21Y', '26.60Y', '28.14Y', '43.34H', '43.41J', '46.35Y', '49.32Y', '91.30Y', '95.32Y', '01.63Y', '11.07G', '30.11Y', '35.15G', '46.24Y', '46.64H', '47.12G', '66.11Y', '77.40G', '85.33Y', '96.40Y', '10.51J', '14.22Y', '23.31Y', '24.10Y', '27.51Y', '28.11Y', '49.34Y', '52.31Y', '84.30H', '87.30H', '12.00Y', '17.22Y', '22.11Y', '23.52Y', '24.52Y', '28.99Y', '30.20Y', '33.11Y', '33.16Y', '35.11Y', '46.83H', '49.31G', '52.32Y', '60.20H', '61.90Y', '86.94H', '09.90Y', '10.61H', '10.81Y', '13.20Y', '14.23Y', '17.24Y', '20.20Y', '22.21Y', '23.12Y', '23.20Y', '23.51Y', '27.12Y', '27.90Y', '28.25Y', '32.30Y', '33.19Y', '35.40Y', '38.23Y', '42.13H', '46.71H', '46.73Y', '46.83J', '47.11K', '52.10G', '56.11H', '56.40Y', '77.12Y', '77.40H', '84.30J', '85.61Y', '90.31G', '99.00Y', '01.15Y', '10.13G', '10.86Y', '11.06Y', '16.25Y', '16.27Y', '17.11Y', '19.20Y', '20.12Y', '22.12Y', '22.22Y', '22.23Y', '23.64Y', '24.41Y', '24.51Y', '24.53Y', '25.51Y', '25.94Y', '26.20Y', '26.30Y', '27.11Y', '27.31Y', '28.13G', '28.42Y', '28.94Y', '30.31Y', '30.91Y', '33.18H', '35.24Y', '38.22Y', '46.17G', '53.30Y', '61.20Y', '64.22Y', '74.91Y', '90.31H', '91.12Y', '95.40Y', '96.10G', '03.30Y', '05.10Y', '05.20Y', '06.20Y', '07.10Y', '07.21Y', '08.91Y', '08.92Y', '08.99Y', '09.10Y', '10.42Y', '10.62Y', '10.71G', '11.07H', '13.95Y', '16.21Y', '16.22Y', '16.24Y', '16.26Y', '18.11Y', '19.10Y', '20.11Y', '20.13Y', '20.14Y', '20.17Y', '20.51Y', '20.60Y', '22.24Y', '23.11Y', '23.14Y', '23.42Y', '23.43Y', '23.44Y', '23.62Y', '23.65Y', '23.91Y', '24.31Y', '24.32Y', '24.34Y', '24.43Y', '24.44Y', '24.46Y', '25.91Y', '25.92Y', '27.32Y', '28.13H', '28.15Y', '28.21Y', '28.23Y', '28.24Y', '28.91Y', '28.92Y', '28.95Y', '28.96Y', '28.97Y', '30.13Y', '30.32Y', '30.40Y', '30.99Y', '32.11Y', '32.91Y', '33.18G', '35.13Y', '35.15H', '35.16Y', '35.23Y', '38.31Y', '38.32Y', '38.33Y', '42.11Y', '43.42H', '46.19G', '46.36Y', '46.43G', '46.43H', '46.89Y', '49.11Y', '49.12Y', '51.22Y', '60.20G', '64.11Y', '65.30Y', '77.51Y', '77.52Y', '84.21Y', '84.22Y', '84.24Y', '86.97Y', '87.91Y', '91.41Y', '91.42Y', '97.00Y', '98.10Y', '98.20Y'])

In [3]:
import numpy as np

In [22]:
collection_name = "original_cleaned"
code = "68.20H"
rng = np.random.default_rng(1)
size = 1000

records, _ = client.scroll(
    collection_name=collection_name,
    scroll_filter={
        "must": [
            {"key": "code", "match": {"value": code}}
        ]
    },
    with_payload=False,
    with_vectors=False,
    limit=100000
)

ids = [record.id for record in records]

random_ids = rng.choice(ids, size=size, replace=True)

random_points = client.retrieve(
    collection_name=collection_name,
    ids=random_ids,
    with_payload=True,
    with_vectors=True,
)

In [23]:
id_to_points = {}

for p in random_points:
    id_to_points[p.id] = p

In [24]:
final_points = [id_to_points[id] for id in random_ids]

In [26]:
payloads = [point.payload for point in final_points]
vectors = [point.vector for point in final_points]

In [66]:
y = np.append(np.zeros(len(payloads) - 500), np.ones(500))
y.astype(np.float32)
for payload, is_synth in zip(payloads, y):
        payload["is_synth"] = int(is_synth)

In [41]:
selected = rng.choice(100000, size=int(0.8*100000), replace=False)
selected.sort()

In [42]:
not_selected = np.delete(np.arange(100000), selected)

In [18]:
len(final_points)

10000

In [2]:
import numpy as np

In [10]:
rng = np.random.default_rng(1)
indices = np.arange(100000)
indices_train = rng.choice(indices, size=int(0.8*100000), replace=False)
indices_test = np.delete(indices, indices_train)
rng.shuffle(indices_test)

In [11]:
payloads = list(np.linspace(127, 129182, 100000))

In [12]:
payloads_train = [payloads[i] for i in indices_train]
payloads_test = [payloads[i] for i in indices_test]

In [13]:
payloads_test[:10]

[np.float64(65219.121271212716),
 np.float64(8795.711037110372),
 np.float64(77753.06821068212),
 np.float64(105523.40081400814),
 np.float64(74827.36210362104),
 np.float64(73634.8819788198),
 np.float64(72903.13281132812),
 np.float64(101589.76507765078),
 np.float64(38073.421114211145),
 np.float64(3521.1804418044185)]